UPDATE "Team" SET "shortName" = 'Air Force' WHERE name = 'Air Force Falcons';
UPDATE "Team" SET "shortName" = 'Akron' WHERE name = 'Akron Zips';
UPDATE "Team" SET "shortName" = 'Alabama' WHERE name = 'Alabama Crimson Tide';
UPDATE "Team" SET "shortName" = 'App St.' WHERE name = 'Appalachian State Mountaineers';
UPDATE "Team" SET "shortName" = 'Arizona St.' WHERE name = 'Arizona State Sun Devils';
UPDATE "Team" SET "shortName" = 'Arizona' WHERE name = 'Arizona Wildcats';
UPDATE "Team" SET "shortName" = 'Arkansas' WHERE name = 'Arkansas Razorbacks';
UPDATE "Team" SET "shortName" = 'Arkansas St.' WHERE name = 'Arkansas State Red Wolves';
UPDATE "Team" SET "shortName" = 'Army' WHERE name = 'Army Black Knights';
UPDATE "Team" SET "shortName" = 'Auburn' WHERE name = 'Auburn Tigers';
UPDATE "Team" SET "shortName" = 'Ball St.' WHERE name = 'Ball State Cardinals';
UPDATE "Team" SET "shortName" = 'Baylor' WHERE name = 'Baylor Bears';
UPDATE "Team" SET "shortName" = 'Boise St.' WHERE name = 'Boise State Broncos';
UPDATE "Team" SET "shortName" = 'Boston College' WHERE name = 'Boston College Eagles';
UPDATE "Team" SET "shortName" = 'Bowling Green' WHERE name = 'Bowling Green Falcons';
UPDATE "Team" SET "shortName" = 'Buffalo' WHERE name = 'Buffalo Bulls';
UPDATE "Team" SET "shortName" = 'BYU' WHERE name = 'BYU Cougars';
UPDATE "Team" SET "shortName" = 'California' WHERE name = 'California Golden Bears';
UPDATE "Team" SET "shortName" = 'Central Michigan' WHERE name = 'Central Michigan Chippewas';
UPDATE "Team" SET "shortName" = 'Charlotte' WHERE name = 'Charlotte 49ers';
UPDATE "Team" SET "shortName" = 'Cincinnati' WHERE name = 'Cincinnati Bearcats';
UPDATE "Team" SET "shortName" = 'Clemson' WHERE name = 'Clemson Tigers';
UPDATE "Team" SET "shortName" = 'Coastal Carolina' WHERE name = 'Coastal Carolina Chanticleers';
UPDATE "Team" SET "shortName" = 'Colorado' WHERE name = 'Colorado Buffaloes';
UPDATE "Team" SET "shortName" = 'Colorado St.' WHERE name = 'Colorado State Rams';
UPDATE "Team" SET "shortName" = 'Duke' WHERE name = 'Duke Blue Devils';
UPDATE "Team" SET "shortName" = 'East Carolina' WHERE name = 'East Carolina Pirates';
UPDATE "Team" SET "shortName" = 'Eastern Michigan' WHERE name = 'Eastern Michigan Eagles';
UPDATE "Team" SET "shortName" = 'Florida Atlantic' WHERE name = 'Florida Atlantic Owls';
UPDATE "Team" SET "shortName" = 'Florida' WHERE name = 'Florida Gators';
UPDATE "Team" SET "shortName" = 'FIU' WHERE name = 'Florida International Panthers';
UPDATE "Team" SET "shortName" = 'Florida St.' WHERE name = 'Florida State Seminoles';
UPDATE "Team" SET "shortName" = 'Fresno St.' WHERE name = 'Fresno State Bulldogs';
UPDATE "Team" SET "shortName" = 'Georgia' WHERE name = 'Georgia Bulldogs';
UPDATE "Team" SET "shortName" = 'Georgia Southern' WHERE name = 'Georgia Southern Eagles';
UPDATE "Team" SET "shortName" = 'Georgia St.' WHERE name = 'Georgia State Panthers';
UPDATE "Team" SET "shortName" = 'Georgia Tech' WHERE name = 'Georgia Tech Yellow Jackets';
UPDATE "Team" SET "shortName" = 'Hawaii' WHERE name = 'Hawaii Rainbow Warriors';
UPDATE "Team" SET "shortName" = 'Houston' WHERE name = 'Houston Cougars';
UPDATE "Team" SET "shortName" = 'Illinois' WHERE name = 'Illinois Fighting Illini';
UPDATE "Team" SET "shortName" = 'Indiana' WHERE name = 'Indiana Hoosiers';
UPDATE "Team" SET "shortName" = 'Iowa' WHERE name = 'Iowa Hawkeyes';
UPDATE "Team" SET "shortName" = 'Iowa St.' WHERE name = 'Iowa State Cyclones';
UPDATE "Team" SET "shortName" = 'Kansas' WHERE name = 'Kansas Jayhawks';
UPDATE "Team" SET "shortName" = 'Kansas St.' WHERE name = 'Kansas State Wildcats';
UPDATE "Team" SET "shortName" = 'Kent St.' WHERE name = 'Kent State Golden Flashes';
UPDATE "Team" SET "shortName" = 'Kentucky' WHERE name = 'Kentucky Wildcats';
UPDATE "Team" SET "shortName" = 'Liberty' WHERE name = 'Liberty Flames';
UPDATE "Team" SET "shortName" = 'Louisiana' WHERE name = 'Louisiana Ragin'' Cajuns';
UPDATE "Team" SET "shortName" = 'Louisiana Tech' WHERE name = 'Louisiana Tech Bulldogs';
UPDATE "Team" SET "shortName" = 'Louisville' WHERE name = 'Louisville Cardinals';
UPDATE "Team" SET "shortName" = 'LSU' WHERE name = 'LSU Tigers';
UPDATE "Team" SET "shortName" = 'Marshall' WHERE name = 'Marshall Thundering Herd';
UPDATE "Team" SET "shortName" = 'Maryland' WHERE name = 'Maryland Terrapins';
UPDATE "Team" SET "shortName" = 'Memphis' WHERE name = 'Memphis Tigers';
UPDATE "Team" SET "shortName" = 'Miami' WHERE name = 'Miami Hurricanes';
UPDATE "Team" SET "shortName" = 'Miami (OH)' WHERE name = 'Miami (OH) RedHawks';
UPDATE "Team" SET "shortName" = 'Michigan St.' WHERE name = 'Michigan State Spartans';
UPDATE "Team" SET "shortName" = 'Michigan' WHERE name = 'Michigan Wolverines';
UPDATE "Team" SET "shortName" = 'Middle Tennessee' WHERE name = 'Middle Tennessee Blue Raiders';
UPDATE "Team" SET "shortName" = 'Minnesota' WHERE name = 'Minnesota Golden Gophers';
UPDATE "Team" SET "shortName" = 'Mississippi St.' WHERE name = 'Mississippi State Bulldogs';
UPDATE "Team" SET "shortName" = 'Missouri' WHERE name = 'Missouri Tigers';
UPDATE "Team" SET "shortName" = 'Navy' WHERE name = 'Navy Midshipmen';
UPDATE "Team" SET "shortName" = 'NC St.' WHERE name = 'NC State Wolfpack';
UPDATE "Team" SET "shortName" = 'Nebraska' WHERE name = 'Nebraska Cornhuskers';
UPDATE "Team" SET "shortName" = 'Nevada' WHERE name = 'Nevada Wolf Pack';
UPDATE "Team" SET "shortName" = 'New Mexico' WHERE name = 'New Mexico Lobos';
UPDATE "Team" SET "shortName" = 'North Carolina' WHERE name = 'North Carolina Tar Heels';
UPDATE "Team" SET "shortName" = 'North Texas' WHERE name = 'North Texas Mean Green';
UPDATE "Team" SET "shortName" = 'Northern Illinois' WHERE name = 'Northern Illinois Huskies';
UPDATE "Team" SET "shortName" = 'Northwestern' WHERE name = 'Northwestern Wildcats';
UPDATE "Team" SET "shortName" = 'Notre Dame' WHERE name = 'Notre Dame Fighting Irish';
UPDATE "Team" SET "shortName" = 'Ohio' WHERE name = 'Ohio Bobcats';
UPDATE "Team" SET "shortName" = 'Ohio St.' WHERE name = 'Ohio State Buckeyes';
UPDATE "Team" SET "shortName" = 'Oklahoma' WHERE name = 'Oklahoma Sooners';
UPDATE "Team" SET "shortName" = 'Oklahoma St.' WHERE name = 'Oklahoma State Cowboys';
UPDATE "Team" SET "shortName" = 'Old Dominion' WHERE name = 'Old Dominion Monarchs';
UPDATE "Team" SET "shortName" = 'Ole Miss' WHERE name = 'Ole Miss Rebels';
UPDATE "Team" SET "shortName" = 'Oregon' WHERE name = 'Oregon Ducks';
UPDATE "Team" SET "shortName" = 'Oregon St.' WHERE name = 'Oregon State Beavers';
UPDATE "Team" SET "shortName" = 'Penn St.' WHERE name = 'Penn State Nittany Lions';
UPDATE "Team" SET "shortName" = 'Pittsburgh' WHERE name = 'Pittsburgh Panthers';
UPDATE "Team" SET "shortName" = 'Purdue' WHERE name = 'Purdue Boilermakers';
UPDATE "Team" SET "shortName" = 'Rice' WHERE name = 'Rice Owls';
UPDATE "Team" SET "shortName" = 'Rutgers' WHERE name = 'Rutgers Scarlet Knights';
UPDATE "Team" SET "shortName" = 'San Diego St.' WHERE name = 'San Diego State Aztecs';
UPDATE "Team" SET "shortName" = 'San Jose St.' WHERE name = 'San Jose State Spartans';
UPDATE "Team" SET "shortName" = 'SMU' WHERE name = 'SMU Mustangs';
UPDATE "Team" SET "shortName" = 'South Alabama' WHERE name = 'South Alabama Jaguars';
UPDATE "Team" SET "shortName" = 'South Carolina' WHERE name = 'South Carolina Gamecocks';
UPDATE "Team" SET "shortName" = 'South Florida' WHERE name = 'South Florida Bulls';
UPDATE "Team" SET "shortName" = 'Southern Miss' WHERE name = 'Southern Miss Golden Eagles';
UPDATE "Team" SET "shortName" = 'Stanford' WHERE name = 'Stanford Cardinal';
UPDATE "Team" SET "shortName" = 'Syracuse' WHERE name = 'Syracuse Orange';
UPDATE "Team" SET "shortName" = 'TCU' WHERE name = 'TCU Horned Frogs';
UPDATE "Team" SET "shortName" = 'Temple' WHERE name = 'Temple Owls';
UPDATE "Team" SET "shortName" = 'Tennessee' WHERE name = 'Tennessee Volunteers';
UPDATE "Team" SET "shortName" = 'Texas A&M' WHERE name = 'Texas AM Aggies';
UPDATE "Team" SET "shortName" = 'Texas' WHERE name = 'Texas Longhorns';
UPDATE "Team" SET "shortName" = 'Texas St.' WHERE name = 'Texas State Bobcats';
UPDATE "Team" SET "shortName" = 'Texas Tech' WHERE name = 'Texas Tech Red Raiders';
UPDATE "Team" SET "shortName" = 'Toledo' WHERE name = 'Toledo Rockets';
UPDATE "Team" SET "shortName" = 'Troy' WHERE name = 'Troy Trojans';
UPDATE "Team" SET "shortName" = 'Tulane' WHERE name = 'Tulane Green Wave';
UPDATE "Team" SET "shortName" = 'Tulsa' WHERE name = 'Tulsa Golden Hurricane';
UPDATE "Team" SET "shortName" = 'UAB' WHERE name = 'UAB Blazers';
UPDATE "Team" SET "shortName" = 'UCF' WHERE name = 'UCF Knights';
UPDATE "Team" SET "shortName" = 'UCLA' WHERE name = 'UCLA Bruins';
UPDATE "Team" SET "shortName" = 'UNLV' WHERE name = 'UNLV Rebels';
UPDATE "Team" SET "shortName" = 'USC' WHERE name = 'USC Trojans';
UPDATE "Team" SET "shortName" = 'Utah St.' WHERE name = 'Utah State Aggies';
UPDATE "Team" SET "shortName" = 'Utah' WHERE name = 'Utah Utes';
UPDATE "Team" SET "shortName" = 'UTEP' WHERE name = 'UTEP Miners';
UPDATE "Team" SET "shortName" = 'UTSA' WHERE name = 'UTSA Roadrunners';
UPDATE "Team" SET "shortName" = 'Vanderbilt' WHERE name = 'Vanderbilt Commodores';
UPDATE "Team" SET "shortName" = 'Virginia' WHERE name = 'Virginia Cavaliers';
UPDATE "Team" SET "shortName" = 'Virginia Tech' WHERE name = 'Virginia Tech Hokies';
UPDATE "Team" SET "shortName" = 'Wake Forest' WHERE name = 'Wake Forest Demon Deacons';
UPDATE "Team" SET "shortName" = 'Washington' WHERE name = 'Washington Huskies';
UPDATE "Team" SET "shortName" = 'Washington St.' WHERE name = 'Washington State Cougars';
UPDATE "Team" SET "shortName" = 'West Virginia' WHERE name = 'West Virginia Mountaineers';
UPDATE "Team" SET "shortName" = 'Western Kentucky' WHERE name = 'Western Kentucky Hilltoppers';
UPDATE "Team" SET "shortName" = 'Western Michigan' WHERE name = 'Western Michigan Broncos';
UPDATE "Team" SET "shortName" = 'Wisconsin' WHERE name = 'Wisconsin Badgers';
UPDATE "Team" SET "shortName" = 'Wyoming' WHERE name = 'Wyoming Cowboys';
